# flake8: noqa
# Generated by Django 4.2.4 on 2023-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(max_length=255)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(blank=True,
                 null=True, upload_to='product_image/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('marketing_price', models.FloatField()),
                ('marketing_off_price', models.FloatField(default=0)),
                ('product_type', models.CharField(choices=[
                 ('V', 'Variable'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
