# Generated by Django 4.2.4 on 2023-08-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(max_length=12, verbose_name='SSN'),
        ),
    ]
